import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, AppState, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

const API=(process.env.EXPO_PUBLIC_API_URL||'http://127.0.0.1:8000').replace(/\/$/,'');
let AUTH_TOKEN='';
async function request(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(AUTH_TOKEN?{Authorization:`Bearer ${AUTH_TOKEN}`}:{ }),...(options.headers||{})}});let d={};try{d=await r.json();}catch{}if(!r.ok)throw new Error(d.detail||`Request failed (${r.status})`);return d;}
const dt=v=>v?new Date(v):null;
const short=v=>dt(v)?.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})||'';
const time=v=>dt(v)?.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})||'';
const full=v=>dt(v)?.toLocaleString([],{weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})||'';
const toneFor=s=>s==='Confirmed'?'ok':s==='Mixed evidence'?'warn':s==='Denied'?'danger':s==='Bad data'?'warn':'plain';
function Loading(){return <ActivityIndicator style={{marginTop:50}}/>} function Err({children}){return children?<Text style={S.error}>{children}</Text>:null}
function Pill({children,tone='plain'}){return <View style={[S.pill,S[`pill_${tone}`]]}><Text style={[S.pillText,S[`pillText_${tone}`]]}>{children}</Text></View>}
function Card({children,style}){return <View style={[S.card,style]}>{children}</View>}
function Rule(){return <View style={S.rule}/>}
function Section({children}){return <Text style={S.section}>{children}</Text>}
function Brand(){return <View style={S.brandWrap}><View style={S.logoMark}><Text style={S.logoWolf}>🐺</Text><Text style={S.logoGlass}>⌕</Text></View><View><Text style={S.brand}>Sherlock Howls</Text><Text style={S.tag}>Your body leaves clues.</Text></View></View>}

function Login({onLogin}){const[u,setU]=useState(''),[p,setP]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const go=async()=>{if(!u.trim()||!p)return;setBusy(true);setError('');try{const d=await request('/api/auth/login',{method:'POST',body:JSON.stringify({username:u.trim(),password:p})});AUTH_TOKEN=d.token;onLogin(d.user)}catch(e){setError(e.message)}finally{setBusy(false)}};return <KeyboardAvoidingView style={S.login} behavior={Platform.OS==='ios'?'padding':undefined}><View style={S.loginBox}><Brand/><Text style={S.loginLead}>Sign in to open your casebook.</Text><Text style={S.label}>USERNAME</Text><TextInput style={S.inputBox} value={u} onChangeText={setU} autoCapitalize="none" autoCorrect={false} placeholder="Enter your username"/><Text style={S.label}>PASSWORD</Text><TextInput style={S.inputBox} value={p} onChangeText={setP} secureTextEntry placeholder="Enter your password" onSubmitEditing={go}/><Err>{error}</Err><Pressable style={S.primary} onPress={go} disabled={busy}>{busy?<ActivityIndicator color="#fff"/>:<Text style={S.primaryText}>Sign in</Text>}</Pressable><Text style={S.small}>Each account is mapped to one participant.</Text></View></KeyboardAvoidingView>}
function Header({user,onSignOut,onSync,syncing,lastSynced}){return <View style={S.header}><Brand/><View style={{alignItems:'flex-end'}}><Text style={S.user}>{user.name}</Text><View style={S.headerActions}><Pressable onPress={onSync} disabled={syncing}><Text style={S.link}>{syncing?'Syncing…':'Sync'}</Text></Pressable><Text style={S.headerDot}>·</Text><Pressable onPress={onSignOut}><Text style={S.link}>Sign out</Text></Pressable></View>{lastSynced?<Text style={S.syncMeta}>Last synced {lastSynced.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text>:null}</View></View>}

function PatternCard({p,update}){if(!p)return null;return <Card style={S.pattern}><View style={S.row}><Text style={S.caseNo}>CASE FILE · {p.hyp_id}</Text>{update?.ts?<Text style={S.meta}>{short(update.ts)} · {time(update.ts)}</Text>:null}</View><View style={S.pills}><Pill>{p.lab_name}</Pill><Pill tone={toneFor(p.status_label)}>{p.status_label}</Pill>{['testing','fading'].includes(p.status)?<Pill tone="accent">Tracking automatically</Pill>:null}</View><Text style={S.cardTitle}>{p.display_title}</Text>{p.origin?<Text style={S.muted}>{p.origin}</Text>:null}<Text style={S.evidence}>{p.supports||0} matched · {p.contradicts||0} didn’t match</Text></Card>}
function Feed({m}){if(m.pattern)return <PatternCard p={m.pattern} update={m}/>;const label={discovery:'Confirmed',case:'Possible link',rejected:'Denied',fading:'Mixed evidence'}[m.kind]||m.kind;return <Card><View style={S.pills}><Pill tone={toneFor(label)}>{label}</Pill><Pill>{m.lab_name||m.lab}</Pill></View><Text style={S.cardTitle}>{String(m.title||'').replace('Not confirmed:','Denied:').replace('Fading:','Mixed evidence:').replace('Case solved','Possible link')}</Text><Text style={S.muted}>{m.body}</Text></Card>}
function Labs({labs}){const labTone=k=>k==='fuel'?'glucose':k==='stress'?'warn':k==='sleep'?'accent':k==='movement'?'ok':'plain';return <View style={S.labGrid}>{(labs||[]).map(l=><View key={l.key} style={S.lab}><Text style={S.labTitle}>{l.name}</Text><Text style={S.muted}>{l.situation}s</Text>{l.key==='stress'?<Text style={S.small}>stress 1–10, personal ⓘ</Text>:null}<View style={[S.pills,{marginTop:'auto'}]}><Pill tone={labTone(l.key)}>{l.cards} cards</Pill><Pill>{l.open} open</Pill></View></View>)}</View>}
function Today({pid,user,refreshKey,onLoaded}){const[d,setD]=useState(null),[e,setE]=useState('');useEffect(()=>{request(`/api/today/${pid}`).then(setD).catch(x=>setE(x.message))},[pid,refreshKey]);useEffect(()=>{if(d)onLoaded?.()},[d]);if(!d&&!e)return <Loading/>;const r=d?.rank||{};return <ScrollView contentContainerStyle={S.content}><Text style={S.title}>Daily briefing</Text><Text style={S.sub}>{user.name} · {full(d?.as_of)} in the replay</Text><Err>{e}</Err><Section>New clues today</Section>{d?.messages?.length?d.messages.map((m,i)=><Feed key={i} m={m}/>):<Card><Text style={S.label}>NO NEW CLUES TODAY</Text><Text style={S.muted}>New possible links and pattern updates will appear here.</Text></Card>}<Card><Text style={S.label}>CLOSED QUIETLY TODAY</Text><Text style={S.body}>{d?.closed_quietly?.unexplained||0} surprise{d?.closed_quietly?.unexplained===1?'':'s'} with no clear reason · {d?.closed_quietly?.bad_data||0} dismissed as bad data</Text><Text style={S.muted}>No alerts were sent for these. Details are in the Casebook.</Text></Card><Section>Detective rank</Section><Card><Text style={S.big}>{r.name}</Text><Text style={S.muted}>{r.points} points · {r.next_rank_points?`${r.next_rank_points-r.points} points to the next rank`:'Top rank reached'}</Text></Card><Section>Quests · optional</Section>{d?.quests?.length?d.quests.map((q,i)=><Card key={i}><View style={S.pills}><Pill>{q.lab}</Pill><Pill tone={q.done?'ok':'accent'}>{q.done?'Completed':'Tracking automatically'}</Pill></View><Text style={S.cardTitle}>{q.title}</Text><Text style={S.evidence}>{q.progress} of {q.target}</Text></Card>):<Card><Text style={S.muted}>No quests currently</Text></Card>}<Section>Your labs</Section><Labs labs={d?.labs}/></ScrollView>}

function Cases({pid,refreshKey,onLoaded}){const[list,setList]=useState(null),[id,setId]=useState(null),[detail,setDetail]=useState(null),[e,setE]=useState('');useEffect(()=>{request(`/api/cases/${pid}`).then(x=>setList(x.cases)).catch(x=>setE(x.message))},[pid,refreshKey]);useEffect(()=>{if(list)onLoaded?.()},[list]);useEffect(()=>{if(id){setDetail(null);request(`/api/case/${pid}/${encodeURIComponent(id)}`).then(x=>setDetail(x.case)).catch(x=>setE(x.message))}},[id,pid]);if(!list&&!e)return <Loading/>;if(id)return <ScrollView contentContainerStyle={S.content}><Pressable onPress={()=>{setId(null);setDetail(null)}}><Text style={S.link}>‹ Cases</Text></Pressable>{!detail?<Loading/>:<><View style={S.pills}><Pill>{detail.lab_name} Lab</Pill><Pill tone={toneFor(detail.status_label)}>{detail.status_label}</Pill></View><Text style={S.title}>{detail.display_title||detail.title}</Text><Text style={S.sub}>Observation · {full(detail.ts)}</Text>{detail.hypothesis?<Card><Text style={S.label}>EXPLANATION AT THE TIME</Text><Text style={S.body}>{detail.message}</Text></Card>:<Text style={S.body}>{detail.message}</Text>}<Text style={S.meta}>{detail.event_id} · agent: {detail.agent||''}</Text>{detail.tools?.length?<Card><Text style={S.label}>AGENT STEPS</Text><Text style={S.body}>{detail.tools.join(' → ')}</Text></Card>:null}{detail.checks?.length?<Card><Text style={S.label}>STEP 1 · DATA CHECK</Text>{detail.checks.map((c,i)=><View key={i} style={S.check}><Text style={{color:c.passed?C.ok:C.danger,fontWeight:'900'}}>{c.passed?'✓':'×'}</Text><Text style={S.body}><Text style={{fontWeight:'800'}}>{c.check}: </Text>{c.detail}</Text></View>)}</Card>:null}{detail.differences?.length?<Card><Text style={S.label}>STEP 2 · WHAT WAS DIFFERENT</Text>{detail.differences.slice(0,5).map((x,i)=><View key={i} style={{gap:4}}><View style={S.row}><Text style={S.cardTitle}>{x.label}</Text><Pill tone={x.level==='very unusual'?'danger':x.level==='somewhat'?'warn':'plain'}>{x.level}</Pill></View><Text style={S.muted}>this time {x.this_time_text??x.this_time} · typical {x.typical_text??x.similar_median}</Text></View>)}</Card>:null}{detail.hypothesis?<><Section>Step 3 · Link status</Section><PatternCard p={detail.hypothesis}/></>:null}</>}</ScrollView>;return <ScrollView contentContainerStyle={S.content}><Text style={S.title}>Cases</Text><Err>{e}</Err>{list?.length?list.map(x=><Pressable key={x.event_id} style={S.card} onPress={()=>setId(x.event_id)}><View style={S.row}><View style={S.pills}><Pill>{x.lab_name}</Pill><Pill tone={toneFor(x.status_label)}>{x.status_label}</Pill></View><Text style={S.meta}>{short(x.ts)}</Text></View><Text style={S.cardTitle}>{x.display_title||x.title}</Text><Text style={S.link}>Open case ›</Text></Pressable>):<Card><Text style={S.muted}>No cases investigated yet.</Text></Card>}</ScrollView>}

function Findings({pid,refreshKey,onLoaded}){const[d,setD]=useState(null),[e,setE]=useState('');useEffect(()=>{request(`/api/discoveries/${pid}`).then(setD).catch(x=>setE(x.message))},[pid,refreshKey]);useEffect(()=>{if(d)onLoaded?.()},[d]);if(!d&&!e)return <Loading/>;return <ScrollView contentContainerStyle={S.content}><Text style={S.title}>Findings · {d?.discoveries?.length||0} collected</Text><Err>{e}</Err><View style={S.pills}><Pill tone="gold">Legendary {d?.counts?.legendary||0}</Pill><Pill tone="accent">Rare {d?.counts?.rare||0}</Pill><Pill>Common {d?.counts?.common||0}</Pill></View>{d?.discoveries?.map((x,i)=><Card key={x.card_id||i} style={x.status==='fading'?S.fading:null}><View style={S.pills}><Pill tone={x.rarity==='legendary'?'gold':x.rarity==='rare'?'accent':'plain'}>{x.rarity?.[0]?.toUpperCase()+x.rarity?.slice(1)} · {x.lab_name}</Pill><Pill tone={x.status==='fading'?'warn':'ok'}>{x.status_label}</Pill></View><Text style={S.cardTitle}>{x.title}</Text><Text style={S.muted}>{x.claim}</Text>{x.effect_text?<Text style={S.big}>{x.effect_text}</Text>:null}<Text style={S.evidence}>{x.evidence}</Text></Card>)}{d?.close?.map((h,i)=><PatternCard key={`c${i}`} p={h}/>)}{d?.rejected_titles?.length?<Text style={S.muted}>Denied after newer data disagreed: {d.rejected_titles.join(', ')}</Text>:null}</ScrollView>}

function Hyp({h}){const[open,setOpen]=useState(false);return <Pressable onPress={()=>setOpen(!open)}><PatternCard p={h}/>{open?<Card style={{marginTop:-7}}><Text style={S.label}>EVIDENCE LOG · {h.hyp_id}</Text>{h.evidence?.length?h.evidence.map((x,i)=><Text key={i} style={S.muted}>{short(x.ts)} · {x.verdict==='supports'?'Matched':x.verdict==='contradicts'?"Didn't match":'No clear result'}</Text>):<Text style={S.muted}>No comparisons recorded yet.</Text>}</Card>:null}</Pressable>}
function Casebook({pid,refreshKey,onLoaded}){const[d,setD]=useState(null),[e,setE]=useState('');useEffect(()=>{request(`/api/notebook/${pid}`).then(setD).catch(x=>setE(x.message))},[pid,refreshKey]);useEffect(()=>{if(d)onLoaded?.()},[d]);if(!d&&!e)return <Loading/>;const un=(d?.hypotheses||[]).filter(h=>h.status!=='confirmed'),con=(d?.hypotheses||[]).filter(h=>h.status==='confirmed'),f=d?.funnel||{};return <ScrollView contentContainerStyle={S.content}><Text style={S.title}>Casebook</Text><Err>{e}</Err><Section>Unconfirmed · {un.length}</Section>{un.length?un.map(h=><Hyp key={h.hyp_id} h={h}/>):<Text style={S.muted}>No open investigations.</Text>}<Section>Confirmed · {con.length}</Section>{con.length?con.map(h=><Hyp key={h.hyp_id} h={h}/>):<Text style={S.muted}>No confirmed patterns yet.</Text>}<Section>Every surprise so far</Section><Card>{[['Surprising events','surprises'],['Bad data, dismissed','bad_data'],['No clear reason','unexplained'],['Became leads','leads'],['Confirmed discoveries','discoveries']].map(([l,k],i)=><React.Fragment key={k}><View style={S.row}><Text style={S.body}>{l}</Text><Text style={S.stat}>{f[k]||0}</Text></View>{i<4?<Rule/>:null}</React.Fragment>)}<Text style={S.muted}>Most surprises are noise or bad data. Only repeated patterns become discoveries.</Text></Card><Card><Text style={S.label}>SITUATIONS WATCHED</Text><Text style={S.big}>{d?.situations_watched||0}</Text><Text style={S.muted}>{d?.situations_good_data||0} passed the data check and counted as natural experiments.</Text></Card></ScrollView>}

function Chat({pid}){const starters=['What have you learned about me so far?','Which hypothesis has the strongest evidence?','Have any of your ideas been proven wrong?','What should Sherlock Howls investigate next?'];const[m,setM]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false);const ref=useRef(null);const send=async raw=>{const q=(raw??text).trim();if(!q||busy)return;const hist=m.slice(-8),next=[...m,{role:'user',content:q}];setM(next);setText('');setBusy(true);try{const d=await request('/api/chat',{method:'POST',body:JSON.stringify({participant_id:pid,message:q,history:hist})});setM([...next,{role:'assistant',content:d.answer}])}catch(e){setM([...next,{role:'assistant',content:`I couldn't query the Sherlock Howls notebook right now. ${e.message}`}])}finally{setBusy(false)}};return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined} keyboardVerticalOffset={80}><ScrollView ref={ref} contentContainerStyle={S.content} onContentSizeChange={()=>ref.current?.scrollToEnd({animated:true})}><Text style={S.title}>Ask Sherlock Howls</Text><Text style={S.sub}>Ask about patterns, discoveries, hypotheses, and cases Sherlock Howls has actually observed in your data.</Text>{!m.length?<><Section>Try asking</Section>{starters.map(q=><Pressable key={q} style={S.card} onPress={()=>send(q)}><Text style={S.body}>{q}</Text></Pressable>)}</>:null}{m.map((x,i)=><View key={i} style={[S.bubble,x.role==='user'?S.userBubble:S.botBubble]}><Text style={[S.body,x.role==='user'&&{color:'#fff'}]}>{x.content}</Text></View>)}{busy?<ActivityIndicator/>:null}</ScrollView><View style={S.composer}><TextInput style={S.chatInput} value={text} onChangeText={setText} placeholder="Ask about your Sherlock Howls data…" multiline/><Pressable style={S.send} onPress={()=>send()}><Text style={{color:'#fff',fontSize:20}}>↑</Text></Pressable></View></KeyboardAvoidingView>}

const TABS=[['today','Today','●'],['cases','Cases','◇'],['findings','Findings','★'],['casebook','Casebook','▤'],['chat','Ask','◉']];
function Nav({tab,setTab}){return <View style={S.nav}>{TABS.map(([k,l,i])=><Pressable key={k} style={S.navItem} onPress={()=>setTab(k)}><Text style={[S.navIcon,tab===k&&S.active]}>{i}</Text><Text style={[S.navLabel,tab===k&&S.active]}>{l}</Text></Pressable>)}</View>}
export default function App(){const[user,setUser]=useState(null),[tab,setTab]=useState('today'),[refreshKey,setRefreshKey]=useState(0),[syncing,setSyncing]=useState(false),[lastSynced,setLastSynced]=useState(null);const sync=()=>{if(!user)return;setSyncing(true);setRefreshKey(k=>k+1)};const loaded=()=>{setSyncing(false);setLastSynced(new Date())};useEffect(()=>{if(!user)return;sync();const timer=setInterval(sync,2000);const sub=AppState.addEventListener('change',state=>{if(state==='active')sync()});return()=>{clearInterval(timer);sub.remove()}},[user]);if(!user)return <View style={S.safe}><StatusBar style="dark"/><Login onLogin={u=>{setUser(u);setLastSynced(null)}}/></View>;const pid=user.participant_id;const common={pid,refreshKey,onLoaded:loaded};const screens={today:<Today {...common} user={user}/>,cases:<Cases {...common}/>,findings:<Findings {...common}/>,casebook:<Casebook {...common}/>,chat:<Chat pid={pid}/>};return <View style={S.safe}><StatusBar style="dark"/><Header user={user} onSync={sync} syncing={syncing} lastSynced={lastSynced} onSignOut={()=>{AUTH_TOKEN='';setUser(null);setTab('today');setRefreshKey(0);setLastSynced(null)}}/><View style={{flex:1}}>{screens[tab]}</View><Nav tab={tab} setTab={setTab}/></View>}

const C={ink:'#262321',text:'#574e46',muted:'#756b61',line:'rgba(69,50,35,0.16)',bg:'#F5F0E7',card:'#FFFDF8',sunk:'#EEE7DC',acc:'#B5121B',accSoft:'#F8E3E3',glucose:'#B83A32',glucoseSoft:'#FBE6DD',ok:'#2C8556',okSoft:'#E0F1E7',warn:'#A86C12',warnSoft:'#F8ECD6',gold:'#9A6D05',goldSoft:'#F7EDCF'};
const S=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.bg,paddingTop:Platform.OS==='ios'?50:18},
 header:{height:76,paddingHorizontal:18,backgroundColor:C.bg,borderBottomWidth:1,borderBottomColor:C.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
 brandWrap:{flexDirection:'row',alignItems:'center',gap:9},
 logoMark:{width:39,height:39,borderRadius:20,borderWidth:2.5,borderColor:C.acc,backgroundColor:C.card,alignItems:'center',justifyContent:'center',position:'relative'},
 logoWolf:{fontSize:19},logoGlass:{position:'absolute',right:-9,bottom:-9,fontSize:22,fontWeight:'900',color:C.ink,transform:[{rotate:'-42deg'}]},
 brand:{fontSize:21,fontWeight:'700',letterSpacing:-.6,color:C.ink},tag:{fontSize:11.5,color:C.text,marginTop:3},
 user:{fontSize:11.5,fontWeight:'600',color:C.ink},link:{fontSize:12,fontWeight:'600',color:C.acc,marginTop:2},headerActions:{flexDirection:'row',alignItems:'center',gap:5},headerDot:{fontSize:11,color:C.muted},syncMeta:{fontSize:8.5,color:C.muted,marginTop:1},
 login:{flex:1,justifyContent:'center',padding:22},loginBox:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:8,padding:20,gap:9},loginLead:{fontSize:13,lineHeight:19,color:C.text,marginVertical:8},
 label:{fontSize:10.5,fontWeight:'500',letterSpacing:1.05,color:C.muted},inputBox:{height:46,borderWidth:1,borderColor:C.line,borderRadius:8,paddingHorizontal:12,color:C.ink,backgroundColor:C.card},
 primary:{height:46,borderRadius:8,backgroundColor:C.acc,alignItems:'center',justifyContent:'center',marginTop:5},primaryText:{color:'#fff',fontWeight:'600'},small:{fontSize:11,lineHeight:15,color:C.muted},error:{fontSize:12.5,color:C.glucose},
 content:{padding:17,paddingBottom:28,gap:10},title:{fontSize:27,lineHeight:32,fontWeight:'700',letterSpacing:-.4,color:C.ink},sub:{fontSize:12.5,lineHeight:18,color:C.text,marginTop:-4},section:{fontSize:15.5,fontWeight:'600',color:C.ink,marginTop:8},
 card:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:8,paddingHorizontal:16,paddingVertical:14,gap:7,shadowColor:'#453223',shadowOpacity:.035,shadowRadius:3,shadowOffset:{width:0,height:2}},pattern:{borderLeftWidth:1,borderTopWidth:1.5,borderTopColor:C.acc},fading:{opacity:.7},
 cardTitle:{fontSize:15.5,lineHeight:21,fontWeight:'600',color:C.ink,flexShrink:1},body:{fontSize:13,lineHeight:19,color:C.ink},muted:{fontSize:13,lineHeight:18,color:C.text},meta:{fontSize:11,color:C.muted},caseNo:{fontSize:10.5,fontWeight:'500',letterSpacing:.7,color:C.muted},big:{fontSize:28,lineHeight:31,fontWeight:'700',color:C.ink},evidence:{fontSize:12.5,fontWeight:'500',color:C.text},stat:{fontSize:15,fontWeight:'600',color:C.ink},
 row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},pills:{flexDirection:'row',flexWrap:'wrap',gap:4},pill:{paddingHorizontal:8,paddingVertical:3,borderRadius:99,backgroundColor:C.sunk},pill_plain:{backgroundColor:C.sunk},pill_ok:{backgroundColor:C.okSoft},pill_warn:{backgroundColor:C.warnSoft},pill_danger:{backgroundColor:C.glucoseSoft},pill_accent:{backgroundColor:C.accSoft},pill_gold:{backgroundColor:C.goldSoft},pill_glucose:{backgroundColor:C.glucoseSoft},
 pillText:{fontSize:10.5,fontWeight:'600',color:C.text},pillText_plain:{color:C.text},pillText_ok:{color:C.ok},pillText_warn:{color:C.warn},pillText_danger:{color:C.glucose},pillText_accent:{color:C.acc},pillText_gold:{color:C.gold},pillText_glucose:{color:C.glucose},
 rule:{height:1,backgroundColor:C.line,marginVertical:4},labGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},lab:{width:'48.5%',minHeight:112,backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:8,padding:13,gap:4},labTitle:{fontSize:15.5,fontWeight:'600',color:C.ink},check:{flexDirection:'row',alignItems:'flex-start',gap:8},
 bubble:{maxWidth:'88%',borderRadius:8,padding:11},userBubble:{alignSelf:'flex-end',backgroundColor:C.acc},botBubble:{alignSelf:'flex-start',backgroundColor:C.card,borderWidth:1,borderColor:C.line},composer:{padding:9,borderTopWidth:1,borderTopColor:C.line,backgroundColor:C.card,flexDirection:'row',alignItems:'flex-end',gap:7},chatInput:{flex:1,minHeight:40,maxHeight:95,borderWidth:1,borderColor:C.line,borderRadius:8,paddingHorizontal:13,paddingVertical:9,color:C.ink,backgroundColor:C.card},send:{width:40,height:40,borderRadius:8,backgroundColor:C.acc,alignItems:'center',justifyContent:'center'},
 nav:{height:69,paddingBottom:Platform.OS==='ios'?8:3,backgroundColor:C.sunk,borderTopWidth:1,borderTopColor:C.line,flexDirection:'row'},navItem:{flex:1,alignItems:'center',justifyContent:'center',gap:2},navIcon:{fontSize:14,color:C.muted},navLabel:{fontSize:8.5,fontWeight:'600',color:C.muted},active:{color:C.acc}
});
